import { Inter } from "next/font/google";
import "./globals.css";
import Navlink from './components/Navlink.jsx'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Recipes Next.js",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Navlink />
        <main className="flex-grow">{children}</main>
        <footer className="mt-auto text-center bg-gray-200 p-4">
          <small>
            Copyright © 2024 Biskvis. All Rights Reserved.
          </small>
        </footer>
      </body>
    </html>
  );
}

